#!/bin/bash
sudo apt-get update
sudo apt-get upgrade

sudo apt-get -y install \
gnome-settings-daemon \
libaccountsservice-dev \
libgdk-pixbuf2.0-dev \
libgranite-dev \
libgtk-3-dev \
liblightdm-gobject-1-dev \
libmutter-6-0 \
libmutter-6-dev \
libx11-dev \
meson \
valac

pushd third-party
sudo dpkg -i fonts-raleway-elementary_5.1.0-0+34_ubuntu5.0.1_all.deb
sudo dpkg -i elementary-theme_5.1.1-0_r820+pkg314_ubuntu0.4.1.1_all.deb
popd